apiVersion: apps/v1
kind: Deployment
metadata:
  name: multipaper-server-masters
  labels:
    app: multipaperservermasters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multipaperservermasters
  template:
    metadata:
      labels:
        app: multipaperservermasters
    spec:
      containers:
        - name: multipaper-server-master
          image: itzg/minecraft-server
          env:
            - name: TYPE
              value: "CUSTOM"
            - name: EXTRA_ARGS
              value: "5555 25566"
            - name: CUSTOM_SERVER
              value: https://multipaper.io/api/v2/projects/multipaper/versions/1.18.2/builds/92/downloads/MultiPaper-Master-2.8.8-all.jar
          imagePullPolicy: Always
          ports:
            - containerPort: 25566
---
apiVersion: v1
kind: Service
metadata:
  name: multipaperserverworkers
spec:
  ports:
    - name: worker-port
      port: 5555
      targetPort: 5555
      protocol: "TCP"
  selector:
    app: multipaperservermasters

