apiVersion: apps/v1
kind: Deployment
metadata:
  name: multipaper-server-workers
  labels:
    app: multipaperserverworkers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multipaperserverworkers
  template:
    metadata:
      labels:
        app: multipaperserverworkers
    spec:
      containers:
        - name: multipaper-server-worker
          image: itzg/minecraft-server
          env:
            - name: EULA
              value: "true"
            - name: TYPE
              value: "CUSTOM"
            - name: JVM_OPTS
              value: "-DmultipaperMasterAddress=multipaperserverworkers:5555"
            - name: MEMORY
              value: 5G
            - name: USE_AIKAR_FLAGS
              value: "true"
            - name: OPS
              value: "zLupa_0"
            - name: OVERRIDE_OPS
              value: "true"
            - name: MAX_PLAYERS
              value: "500"
            - name: ONLINE_MODE
              value: "false"
            - name: CUSTOM_SERVER
              value: https://multipaper.io/api/v2/projects/multipaper/versions/1.18.2/builds/92/downloads/multipaper-1.18.2-92.jar
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
            - containerPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: server-workers-ingress
spec:
  selector:
    app: multipaperserverworkers
  type: LoadBalancer
  ports:
    - name: worker-proxy-port
      port: 25566
      targetPort: 25565
      protocol: "TCP"